apiVersion: v1
kind: Service
metadata:
  name: svc-wiki-web
  labels:
    run: svc-wiki-web
spec:
  type: NodePort
  selector:
    app: wiki-web
  ports:
  - protocol: TCP
    port: 30010
    nodePort: 30010
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: svc-wiki-sql
  labels:
    run: svc-wiki-sql
spec:
  selector:
    appdb: wiki-sql
  ports:
  - protocol: TCP
    port: 3306
