apiVersion: v1
kind: PersistentVolume
metadata:
  name: vol-wiki
  labels:
    type: local
spec:
  capacity:
    storage: 6Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/var/k8/pv"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vol-wiki-claim
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2.5Gi
